function opengarage()
setGarageOpen(8,true)
setGarageOpen(11,true)
setGarageOpen(12,true)
setGarageOpen(19,true)
setGarageOpen(27,true)
setGarageOpen(32,true)
setGarageOpen(36,true)
setGarageOpen(40,true)
setGarageOpen(41,true)
setGarageOpen(47,true)
end
addEventHandler('onClientResourceStart', getResourceRootElement(),opengarage)


function closegarage()
setGarageOpen(8,false)
setGarageOpen(11,false)
setGarageOpen(12,false)
setGarageOpen(19,false)
setGarageOpen(27,false)
setGarageOpen(32,false)
setGarageOpen(36,false)
setGarageOpen(40,false)
setGarageOpen(41,false)
setGarageOpen(47,false)
outputChatBox( "Pay & Spray garages are now closed.")
end
addEventHandler( "onClientResourceStop", getResourceRootElement( ),closegarage)